# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.BooleanField(default=False, verbose_name='Publish')),
                ('location', models.CharField(max_length=50, verbose_name='Name of the location (for example: Chavez Park, Berkeley CA)')),
                ('lat', models.FloatField(verbose_name='Latitude of the location (for exammple: 37.427)')),
                ('lng', models.FloatField(verbose_name='Longitude of the location (for example: -122.169)')),
                ('interviewer', models.CharField(blank=True, max_length=50, verbose_name='Your first and last name')),
                ('observer', models.CharField(blank=True, max_length=50, verbose_name='Frst and last name of the Observer')),
                ('contact_org', models.URLField(blank=True, verbose_name='For public lands, enter the name of the managing organization (for example, State Park System)')),
                ('videourl', models.URLField(blank=True, verbose_name='Your complete video URL (for example: https://youtu.be/EcSzOnY7uEY)')),
                ('hist_img', models.ImageField(blank=True, upload_to='landtalk/087cafd31fd34ac894a6ddb7825cffaf.hist', verbose_name='Upload a historical image of the location')),
                ('hist_year', models.IntegerField(blank=True, choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Enter the year the historical image was taken')),
                ('hist_caption', models.CharField(blank=True, max_length=200, verbose_name='Write a caption for the historical image')),
                ('curr_img', models.ImageField(blank=True, upload_to='landtalk/db41b7ff956e495e9ea17953bd0c5719.curr', verbose_name='Upload a current image of the location')),
                ('curr_year', models.IntegerField(blank=True, choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Enter the year the current image was taken')),
                ('curr_caption', models.CharField(blank=True, max_length=200, verbose_name='Write a caption for the current image')),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('time_posted', models.DateTimeField(null=True)),
                ('summary', models.TextField(max_length=200, verbose_name='Write a brief summary of the video: Who says what about land and weather (max length 200 characters)')),
                ('look', models.TextField(max_length=200, verbose_name='How did your observer describe the way the place used to look? (max length 200 characters')),
                ('past_do', models.TextField(max_length=200, verbose_name='What are some of the things your observer used to do here? (max length 200 characters')),
                ('current_do', models.TextField(max_length=200, verbose_name='What are some of the things your observer does here now? (max length 200 characters')),
                ('key_words', models.TextField(verbose_name='Add key words, separated by a comma (for example: dry creek, flood in spring, frogs)')),
                ('steward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
