# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtalkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='curr_img',
            field=models.ImageField(blank=True, upload_to='landtalk/53b1e2dfd1aa48c49a99a0a800377b84.curr', verbose_name='Upload a current image of the location'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hist_img',
            field=models.ImageField(blank=True, upload_to='landtalk/cb2ee22df80340138fcbafad37a40609.hist', verbose_name='Upload a historical image of the location'),
        ),
    ]
