# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtalkapp', '0002_auto_20170313_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='curr_img',
            field=models.ImageField(blank=True, upload_to='landtalk/4d6b59c9dab2407a88e070f5b81c4778.curr', verbose_name='Upload a current image of the location'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_do',
            field=models.TextField(max_length=200, verbose_name='What are some of the things your observer does here now? (max length 200 characters)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hist_img',
            field=models.ImageField(blank=True, upload_to='landtalk/597039001ef94e2d8817f7219bdf2cdf.hist', verbose_name='Upload a historical image of the location'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='look',
            field=models.TextField(max_length=200, verbose_name='How did your observer describe the way the place used to look? (max length 200 characters)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='past_do',
            field=models.TextField(max_length=200, verbose_name='What are some of the things your observer used to do here? (max length 200 characters)'),
        ),
    ]
